const datas = [
    {
        id: 1,
        logoImg: '/assets/images/mangoswapLogo.svg',
        logoName: 'Mangoswap',
        description: 'The mango swap coin is the future for crypto currency, it will allow user share and tansact over defi networks with less fees',
        percent: 50,
        amount: 200000,
        shareOwner: "Yes",
        targetAmount: 400000,
        shareOffered: 18000000,
        shares: 3403000,
        totalShare: 30000000,
        valuation: 8000000,
        website: "www.mangoswap.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "san francisco",
            state: "california",
        },
        teamSizeMin: 100,
        teamSizeMax: 500,
        userBase: 50000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Olarenwaju Cesar",
                position: "Co-Founder",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 3,
                name: "Uzo Amanda",
                position: "Head of Growth",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco",
        vision: "Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint",
        found: "17th May, 2019",
        roadmap: [
            {
                id: 1,
                year: "2018",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2019",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2020",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2021",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]
    },
    {
        id: 2,
        logoImg: '/assets/images/MTTLogo.png',
        logoName: 'MTT',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
        percent: 70,
        amount: 255000,
        targetAmount: 600000,
        shareOwner: "Yes",
        shareOffered: 200000000000,
        shares: 5003200,
        totalShare: 100000000,
        valuation: 200000000,
        found: "7th May, 2020",
        website: "www.mtt.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "chicago",
            state: "Illinois",
        },
        teamSizeMin: "90",
        teamSizeMax: "300",
        userBase: 40000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Uzo Amanda",
                position: "Co-Founder",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 3,
                name: "Olarenwaju Cesar",
                position: "Head of Growth",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco",
        vision: "enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint",
        roadmap: [
            {
                id: 1,
                year: "2020",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2021",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2022",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2023",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]

    }
    ,
    {
        id: 3,
        logoImg: '/assets/images/MVCLogo.png',
        logoName: 'MVC',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
        percent: 90,
        amount: 150000,
        targetAmount: 300000,
        shareOwner: "Yes",
        shareOffered: 10000000,
        shares: 4000000,
        totalShare: 500000000,
        valuation: 1600000,
        found: "19th June, 2018",
        website: "www.mvc.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "Portland",
            state: "Oregon",
        },
        teamSizeMin: "150",
        teamSizeMax: "300",
        userBase: 100000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Uzo Amanda",
                position: "Co-Founder",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 3,
                name: "Olarenwaju Cesar",
                position: "Head of Growth",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco",
        vision: "it aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint",
        roadmap: [
            {
                id: 1,
                year: "2020",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2021",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2022",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2023",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]

    }
    ,
    {
        id: 4,
        logoImg: '/assets/images/orovaultlogo.png',
        logoName: 'Oro vault',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
        percent: 40,
        amount: 400000,
        targetAmount: 700000,
        shareOwner: "No",
        shareOffered: 800000000,
        shares: 5500000,
        totalShare: 1000000,
        valuation: 200000,
        found: "4th July, 2019",
        website: "www.orovault.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "New York City",
            state: "New York",
        },
        teamSizeMin: 50,
        teamSizeMax: 200,
        userBase: 4000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Uzo Amanda",
                position: "Co-Founder",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 3,
                name: "Olarenwaju Cesar",
                position: "Head of Growth",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco",
        vision: "Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est si",
        roadmap: [
            {
                id: 1,
                year: "2019",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2020",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2021",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2022",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]
    },
    {
        id: 5,
        logoImg: '/assets/images/RoLogo.png',
        logoName: 'Ro Vault',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
        percent: 80,
        amount: 100000,
        targetAmount: 300000,
        shareOwner: "No",
        shareOffered: 300000000000,
        shares: 6000000,
        totalShare: 400,
        valuation: 700,
        found: "25th June, 2018",
        website: "www.rovault.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "Atlanta",
            state: "Georgia",
        },
        teamSizeMin: 90,
        teamSizeMax: 500,
        userBase: 60000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Uzo Amanda",
                position: "Co-Founder",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 3,
                name: "Olarenwaju Cesar",
                position: "Head of Growth",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        vision: "Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est",
        roadmap: [
            {
                id: 1,
                year: "2019",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2020",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2021",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2022",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]

    },
    {
        id: 6,
        logoImg: '/assets/images/RoLogo.png',
        logoName: 'Ro Vault',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
        percent: 80,
        amount: 100000,
        targetAmount: 300000,
        shareOwner: "No",
        shareOffered: 300000000000,
        shares: 6000000,
        totalShare: 400,
        valuation: 700,
        found: "25th June, 2018",
        website: "www.rovault.com",
        twitterLink: "https://twitter.com/",
        facebookLink: "https://www.facebook.com/",
        linkedInLink: "https://www.linkedin.com/",
        location: {
            city: "Atlanta",
            state: "Georgia",
        },
        teamSizeMin: 90,
        teamSizeMax: 500,
        userBase: 60000000,
        teamMember: [
            {
                id: 1,
                name: "Edmund Kitan",
                position: "Founder",
                photo: "/assets/images/abel.jpg",
            },
            {
                id: 2,
                name: "Uzo Amanda",
                position: "Co-Founder",
                photo: "/assets/images/michelle.jpg",
            },
            {
                id: 3,
                name: "Olarenwaju Cesar",
                position: "Head of Growth",
                photo: "/assets/images/gideon.jpg",
            },
            {
                id: 4,
                name: "Donald Duke",
                position: "Head of Product",
                photo: "/assets/images/marc.jpg",
            },
        ],
        tags: ["Crypto", "Exchanges", "NFT", "Blockchain"],
        about: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        vision: "Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Amet minim mollit non deserunt ullamco est",
        roadmap: [
            {
                id: 1,
                year: "2019",
                date: "Jan 1st",
                title: "Launch",
                target: "Launch on the app store with over 20k users unboarded and 5k monthly active users.",
            },
            {
                id: 2,
                year: "2020",
                date: "Aug 11th",
                title: "Increased",
                target: "Increased MAU to 5M+ users and generated over 400B+ in transaction volume",
            },
            {
                id: 3,
                year: "2021",
                date: "Apr 20th",
                title: "Introduce",
                target: "Introduce merchant tags to allow online retail purchase with crypto.",
            },
            {
                id: 4,
                year: "2022",
                date: "May 25th",
                title: "Release",
                target: "Release the private beta for P2P loan transaction",
            },
        ]

    },

]

export default datas;