export const members = [
  {
    id: 1,
    name: 'Shot',
    position: 'President',
    department: ['Core'],
    photo: '/assets/images/shot.svg',
    startDate: '12/19/2019',
  },
  {
    id: 2,
    name: 'Jillian Lynch',
    position: 'Sponsorship Coordinator',
    department: ['Business'],
    photo: '/assets/images/jillian.jpg',
    startDate: '10/29/2020',
  },
  {
    id: 3,
    name: 'Shad',
    position: 'Secretary',
    department: ['Core'],
    photo: '/assets/images/shadman.jpg',
    startDate: '01/29/2021',
  },
  {
    id: 4,
    name: 'Seef',
    position: 'Head of Degen',
    department: ['Crypto'],
    photo: 'https://minorityprogrammers.com/assets/images/SEEF.svg',
    startDate: '12/01/2019',
  },
  {
    id: 5,
    name: 'Gideon Nnalue',
    position: 'Software Engineer',
    department: ['Development'],
    photo: '/assets/images/gideon.jpg',
    startDate: '01/01/2021',
  },
  {
    id: 6,
    name: 'Tahmid Biswas',
    position: 'Treasurer',
    department: ['Operations'],
    photo: 'assets/images/tahmid%20(1).svg',
    startDate: '01/01/2021',
  },
  {
    id: 7,
    name: 'Kirsten Pomales Langenbrunner',
    position: 'Blockchain Advisor',
    department: ['Crypto'],
    photo: '/assets/images/teams/kirsten_1.png',
    startDate: '02/01/2021',
  },
  {
    id: 8,
    name: 'Minhazul Anas',
    position: 'Investment Analyst',
    department: ['Crypto'],
    photo: '/assets/images/profile.png',
    startDate: '02/01/2021',
  },
  {
    id: 9,
    name: 'Berket Yemaneberhane',
    position: 'Investment Analyst',
    department: ['Crypto'],
    photo: '/assets/images/profile.png',
    startDate: '02/01/2021',
  },
  {
    id: 10,
    name: 'Roshaan Khan',
    position: 'Product/Strategy',
    department: ['Crypto'],
    photo: '/assets/images/roshaan (1).svg',
    startDate: '02/01/2021',
  },
  {
    id: 11,
    name: 'Delawit Assefa',
    position: 'UI/UX Designer',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '02/01/2021',
  },
  {
    id: 12,
    name: 'David Shengqi Zhou',
    position: 'Business Development Intern',
    department: ['Development'],
    photo: 'assets/images/shengqi.svg',
    startDate: '02/22/2021',
    endDate: '05/21/2021',
  },
  {
    id: 13,
    name: 'Daniel Kleiman',
    position: 'Grant Researcher Intern',
    department: ['Operations'],
    photo: 'assets/images/daniel.svg',
    startDate: '02/22/2021',
    endDate: '05/21/2021',
  },
  {
    id: 14,
    name: 'Fahad Zakir',
    position: 'Software Engineer Intern',
    department: ['Development'],
    photo: 'assets/images/fahad.svg',
    startDate: '02/22/2021',
    endDate: '05/21/2021',
  },
  {
    id: 15,
    name: 'Wesley Luong',
    position: 'Web Development Intern',
    department: ['Development'],
    photo: 'https://minorityprogrammers.com/assets/images/wesley.svg',
    startDate: '02/22/2021',
    endDate: '05/21/2021',
  },
  {
    id: 16,
    name: 'Adam Abdelaziz',
    position: 'Grant Researcher Intern',
    department: ['Operations'],
    photo: '/assets/images/profile.png',
    startDate: '03/01/2021',
    endDate: '05/28/2021',
  },
  {
    id: 17,
    name: 'Rami Abouemira',
    position: 'HR Advisor',
    department: ['People'],
    photo: '/assets/images/teams/RAMI_1.png',
    startDate: '03/01/2021',
  },
  {
    id: 18,
    name: 'Edward Torres',
    position: 'UI/UX Designer',
    department: ['Development'],
    photo: '/assets/images/teams/Edward.png',
    startDate: '03/01/2021',
    endDate: '05/28/2021',
  },
  {
    id: 19,
    name: 'Jonathan Kung',
    position: 'Cryptocurrency/Blockchain R&D Intern',
    department: ['Crypto'],
    photo: '/assets/images/Johnathan.svg',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 20,
    name: 'Bhavini Kadiwala',
    position: 'Data Science Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Bhavini_1.png',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 21,
    name: 'Emmanuel Anuge',
    position: 'Graphic Design Intern',
    department: ['Development'],
    photo: '/assets/images/anuge.svg',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 22,
    name: 'Israel Medina',
    position: 'Graphic Design Intern',
    department: ['Development'],
    photo: '/assets/images/israel.svg',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 23,
    name: 'Aileen Wei',
    position: 'Software QA Engineer Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 24,
    name: 'Nalya Shakirova',
    position: 'Software QA Engineer Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 25,
    name: 'Yixuan Feng',
    position: 'Web Development Intern',
    department: ['Development'],
    photo: '/assets/images/teams/yixuan.png',
    startDate: '03/08/2021',
    endDate: '06/04/2021',
  },
  {
    id: 26,
    name: 'Yudi Fitriansyah',
    position: 'Business Development Intern',
    department: ['Business', 'Operations'],
    photo: 'https://minorityprogrammers.com/assets/images/Yudi.svg',
    startDate: '03/15/2021',
    endDate: '06/11/2021',
  },
  {
    id: 27,
    name: 'Violet Cerritelli',
    position: 'Human Resources Intern',
    department: ['Operations'],
    photo: '/assets/images/Violet.svg',
    startDate: '03/15/2021',
    endDate: '06/11/2021',
  },
  {
    id: 28,
    name: 'Bryanna Turman',
    position: 'Social Media Intern',
    department: ['Operations'],
    photo: 'https://minorityprogrammers.com/assets/images/Bryanna.svg',
    startDate: '03/15/2021',
    endDate: '06/11/2021',
  },
  {
    id: 29,
    name: 'Kaleb Kendall',
    position: 'Cryptocurrency/ Blockchain R&D Intern',
    department: ['Crypto'],
    photo: 'https://minorityprogrammers.com/assets/images/Kaleb.svg',
    startDate: '03/22/2021',
    endDate: '06/18/2021',
  },
  {
    id: 30,
    name: 'Jose Tollinchi',
    position: 'Cryptocurrency/ Blockchain R&D Intern',
    department: ['Crypto'],
    photo: 'https://minorityprogrammers.com/assets/images/Jose.svg',
    startDate: '03/22/2021',
    endDate: '06/18/2021',
  },
  {
    id: 31,
    name: 'Vishal Patil',
    position: 'Cryptocurrency/ Blockchain R&D Intern',
    department: ['Crypto'],
    photo: '/assets/images/profile.png',
    startDate: '03/22/2021',
    endDate: '06/18/2021',
  },
  {
    id: 32,
    name: 'Cedrick Mupenzi',
    position: 'Software Engineer',
    department: ['Development'],
    photo: '/assets/images/Cedrick.svg',
    startDate: '03/22/2021',
    endDate: '06/18/2021',
  },
  {
    id: 33,
    name: 'Taylor Sullivan',
    position: 'Data Science Intern',
    department: ['Development'],
    photo: 'https://minorityprogrammers.com/assets/images/taylor.svg',
    startDate: '03/29/2021',
    endDate: '06/25/2021',
  },
  {
    id: 34,
    name: 'Zhengtong Pan',
    position: 'Data Science Intern',
    department: ['Development'],
    photo: '/assets/images/zhengtong.svg',
    startDate: '03/29/2021',
    endDate: '06/25/2021',
  },
  {
    id: 35,
    name: 'Seemaab Mujtaba',
    position: 'Software Engineer',
    department: ['Development'],
    photo: '/assets/images/teams/Seemaab_1.png',
    startDate: '03/29/2021',
    endDate: '06/25/2021',
  },
  {
    id: 36,
    name: 'Stella Zhou',
    position: 'Data Science Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '04/06/2021',
    endDate: '07/02/2021',
  },
  {
    id: 37,
    name: 'Maazin Ahmed',
    position: 'Human Resources Intern',
    department: ['Operations'],
    photo: '/assets/images/teams/Maazin.png',
    startDate: '04/06/2021',
    endDate: '07/02/2021',
  },
  {
    id: 38,
    name: 'Oleg Nosyrev',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Oleg.png',
    startDate: '04/07/2021',
    endDate: '07/09/2021',
  },
  {
    id: 39,
    name: 'Ulysses Milton',
    position: 'Blockchain Engineer Intern',
    department: ['Crypto'],
    photo: '/assets/images/profile.png',
    startDate: '04/12/2021',
    endDate: '07/09/2021',
  },
  {
    id: 40,
    name: 'Yutian Zhang',
    position: 'Software Engineer',
    department: ['Development'],
    photo: '/assets/images/teams/Yutian.png',
    startDate: '04/12/2021',
    endDate: '07/09/2021',
  },
  {
    id: 41,
    name: 'Salma Khairat',
    position: 'Software QA Engineer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Salma.png',
    startDate: '04/12/2021',
    endDate: '07/09/2021',
  },
  {
    id: 42,
    name: 'Bharathi Aravamudhan',
    position: 'Business Development Intern',
    department: ['Business'],
    photo: '/assets/images/teams/Bharathi.png',
    startDate: '04/19/2021',
    endDate: '07/16/2021',
  },
  {
    id: 43,
    name: 'Kalthoum Adam',
    position: 'Data Science Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Kalthoum.png',
    startDate: '04/19/2021',
    endDate: '07/16/2021',
  },
  {
    id: 44,
    name: 'Emmanuel Feleke',
    position: 'Executive Director, MTT',
    department: ['Operations'],
    photo: '/assets/images/profile.png',
    startDate: '04/19/2021',
  },
  {
    id: 45,
    name: 'Laurel Rottman-Yang',
    position: 'Human Resources Intern',
    department: ['Operations'],
    photo: '/assets/images/teams/Laurel.png',
    startDate: '04/19/2021',
    endDate: '07/16/2021',
  },
  {
    id: 46,
    name: 'Atta-Us-Sammad Abbasi',
    position: 'Project Management Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '04/19/2021',
    endDate: '04/30/2021',
  },
  {
    id: 47,
    name: 'Dominique Coronel',
    position: 'Chairman, Minority ThinkTank',
    department: ['Operations'],
    photo: '/assets/images/profile.png',
    startDate: '04/24/2021',
  },
  {
    id: 48,
    name: 'Reethi Abraham',
    position: 'UI/UX Design Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Reethi.png',
    startDate: '05/03/2021',
    endDate: '08/06/2021',
  },
  {
    id: 49,
    name: 'Chalermkhwan Bonnie Nasritha',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Chalermkhwan-Avatar.png',
    startDate: '05/03/2021',
    endDate: '07/30/2021',
  },
  {
    id: 50,
    name: 'Gabrielle Ranieri',
    position: 'Diversity, Equity, & Inclusion Intern',
    department: ['Operations'],
    photo: '/assets/images/teams/Gabrielle.png',
    startDate: '05/17/2021',
    endDate: '08/13/2021',
  },
  {
    id: 51,
    name: 'Francis Song',
    position: 'Blockchain Engineer Intern',
    department: ['Crypto'],
    photo: '/assets/images/teams/Francis.png',
    startDate: '05/10/2021',
    endDate: '08/13/2021',
  },
  {
    id: 52,
    name: 'Carlos Gomez',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Carlos.png',
    startDate: '05/10/2021',
    endDate: '08/13/2021',
  },
  {
    id: 53,
    name: 'Husankhuja Nizomkhujaev',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Husankhuja.png',
    startDate: '05/10/2021',
    endDate: '08/13/2021',
  },
  {
    id: 54,
    name: 'Nick Morris',
    position: 'Board Member, MTT',
    department: ['Operations', 'Crypto'],
    photo: '/assets/images/profile.png',
    startDate: '03/01/2021',
  },
  {
    id: 55,
    name: 'Gabriel Romero',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Gabriel.png',
    startDate: '05/24/2021',
    endDate: '08/27/2021',
  },
  {
    id: 56,
    name: 'Evan Uwao',
    position: 'React Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Evan.png',
    startDate: '05/24/2021',
    endDate: '08/27/2021',
  },
  {
    id: 57,
    name: 'Maurice Muthaka',
    position: 'React Developer Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '05/24/2021',
    endDate: '08/27/2021',
  },
  {
    id: 58,
    name: 'Gillis Linde',
    position: 'Investment Analyst Intern',
    department: ['Business'],
    photo: '/assets/images/teams/Gillis.png',
    startDate: '05/17/2021',
    endDate: '08/20/2021',
  },
  {
    id: 59,
    name: 'Elana Teodoro',
    position: 'UI/UX Design Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Elana.png',
    startDate: '05/31/2021',
    endDate: '09/03/2021',
  },
  {
    id: 60,
    name: 'Barbara Ramos',
    position: 'UI/UX Design Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Barbara.png',
    startDate: '06/07/2021',
    endDate: '09/10/2021',
  },
  {
    id: 61,
    name: 'Selena Shaw',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Selena.png',
    startDate: '06/07/2021',
    endDate: '09/10/2021',
  },
  {
    id: 62,
    name: 'Nasreen Akter',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '06/14/2021',
    endDate: '09/17/2021',
  },
  {
    id: 63,
    name: 'MD Bilal Hossen',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Bilal.png',
    startDate: '06/21/2021',
    endDate: '09/24/2021',
  },
  {
    id: 64,
    name: 'Eboreime ThankGod',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/profile.png',
    startDate: '06/21/2021',
    endDate: '09/24/2021',
  },
  {
    id: 65,
    name: 'Garrett Molle',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Garrett.png',
    startDate: '06/21/2021',
    endDate: '09/24/2021',
  },
  {
    id: 66,
    name: 'Rafiul Hasan Chowdhury',
    position: 'Software Engineer-React Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Rafiul.png',
    startDate: '06/21/2021',
    endDate: '09/24/2021',
  },
  {
    id: 67,
    name: 'Muhammad Shahnewaz',
    position: 'Front End Developer Intern',
    department: ['Development'],
    photo: '/assets/images/teams/Shahnewaz.png',
    startDate: '06/28/2021',
    endDate: '10/01/2021',
  },
  // {
  //     id: 7,
  //     name: "Kaleb Kendall",
  //     position: "Cryptocurrency/ Blockchain R&D Intern",
  //     department: "Crypto",
  //     photo: "https://minorityprogrammers.com/assets/images/Kaleb.svg",
  // },
  // {
  //     id: 8,
  //     name: "Vishal Patil",
  //     position: "Cryptocurrency/ Blockchain R&D Intern",
  //     department: "Crypto",
  //     photo: "https://minorityprogrammers.com/assets/images/vishal.svg",
  // },
  // {
  //     id: 9,
  //     name: "Jose Tollinchi",
  //     position: "Cryptocurrency/ Blockchain R&D Intern",
  //     department: "Crypto",
  //     photo: "https://minorityprogrammers.com/assets/images/Jose.svg",
  // },

  // {
  //     id: 10,
  //     name: "Shengqi Zhou",
  //     position: "Business Development Intern",
  //     department: "Business",
  //     photo: "https://minorityprogrammers.com/assets/images/shengqi.svg",
  // },
  // {
  //     id: 11,
  //     name: "Yudi Fitriansyah",
  //     position: "Business Development Intern",
  //     department: "Business",
  //     photo: "https://minorityprogrammers.com/assets/images/Yudi.svg",
  // },
  // {
  //     id: 12,
  //     name: "Seef Manj",
  //     position: "Techical Recruiter",
  //     department: "Operations",
  //     photo: "https://minorityprogrammers.com/assets/images/SEEF.svg",
  // },
  // {
  //     id: 13,
  //     name: "Bryanna Turman",
  //     position: "Social Media Manager",
  //     department: "Operations",
  //     photo: "https://minorityprogrammers.com/assets/images/Bryanna.svg",
  // },

];
