export const countries = [
  { label: 'Albania', value: 'AL' },
  { label: 'Åland Islands', value: 'AX' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Anguilla', value: 'AI' },
  { label: 'Antarctica', value: 'AQ' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Aruba', value: 'AW' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahamas (the)', value: 'BS' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bermuda', value: 'BM' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia (Plurinational State of)', value: 'BO' },
  { label: 'Bonaire, Sint Eustatius and Saba', value: 'BQ' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Bouvet Island', value: 'BV' },
  { label: 'Brazil', value: 'BR' },
  { label: 'British Indian Ocean Territory (the)', value: 'IO' },
  { label: 'Brunei Darussalam', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cabo Verde', value: 'CV' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cayman Islands (the)', value: 'KY' },
  { label: 'Central African Republic (the)', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Christmas Island', value: 'CX' },
  { label: 'Cocos (Keeling) Islands (the)', value: 'CC' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros (the)', value: 'KM' },
  { label: 'Congo (the Democratic Republic of the)', value: 'CD' },
  { label: 'Congo (the)', value: 'CG' },
  { label: 'Cook Islands (the)', value: 'CK' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Curaçao', value: 'CW' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czechia', value: 'CZ' },
  { label: "Côte d'Ivoire", value: 'CI' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic (the)', value: 'DO' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Falkland Islands (the) [Malvinas]', value: 'FK' },
  { label: 'Faroe Islands (the)', value: 'FO' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'French Guiana', value: 'GF' },
  { label: 'French Polynesia', value: 'PF' },
  { label: 'French Southern Territories (the)', value: 'TF' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambia (the)', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gibraltar', value: 'GI' },
  { label: 'Greece', value: 'GR' },
  { label: 'Greenland', value: 'GL' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guadeloupe', value: 'GP' },
  { label: 'Guam', value: 'GU' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guernsey', value: 'GG' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Heard Island and McDonald Islands', value: 'HM' },
  { label: 'Holy See (the)', value: 'VA' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran (Islamic Republic of)', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Isle of Man', value: 'IM' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jersey', value: 'JE' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: "Korea (the Democratic People's Republic of)", value: 'KP' },
  { label: 'Korea (the Republic of)', value: 'KR' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: "Lao People's Democratic Republic (the)", value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Macao', value: 'MO' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands (the)', value: 'MH' },
  { label: 'Martinique', value: 'MQ' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mayotte', value: 'YT' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia (Federated States of)', value: 'FM' },
  { label: 'Moldova (the Republic of)', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Montserrat', value: 'MS' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands (the)', value: 'NL' },
  { label: 'New Caledonia', value: 'NC' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger (the)', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Niue', value: 'NU' },
  { label: 'Norfolk Island', value: 'NF' },
  { label: 'Northern Mariana Islands (the)', value: 'MP' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Palestine, State of', value: 'PS' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines (the)', value: 'PH' },
  { label: 'Pitcairn', value: 'PN' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Republic of North Macedonia', value: 'MK' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russian Federation (the)', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Réunion', value: 'RE' },
  { label: 'Saint Barthélemy', value: 'BL' },
  { label: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SH' },
  { label: 'Saint Kitts and Nevis', value: 'KN' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Saint Martin (French part)', value: 'MF' },
  { label: 'Saint Pierre and Miquelon', value: 'PM' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC' },
  { label: 'Samoa', value: 'WS' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Sint Maarten (Dutch part)', value: 'SX' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Georgia and the South Sandwich Islands', value: 'GS' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Sudan (the)', value: 'SD' },
  { label: 'Surilabel', value: 'SR' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syrian Arab Republic', value: 'SY' },
  { label: 'Taiwan (Province of China)', value: 'TW' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania, United Republic of', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Timor-Leste', value: 'TL' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tokelau', value: 'TK' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Turks and Caicos Islands (the)', value: 'TC' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates (the)', value: 'AE' },
  { label: 'United Kingdom of Great Britain and Northern Ireland (the)', value: 'GB' },
  { label: 'United States Minor Outlying Islands (the)', value: 'UM' },
  { label: 'United States of America (the)', value: 'US' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Venezuela (Bolivarian Republic of)', value: 'VE' },
  { label: 'Viet Nam', value: 'VN' },
  { label: 'Virgin Islands (British)', value: 'VG' },
  { label: 'Virgin Islands (U.S.)', value: 'VI' },
  { label: 'Wallis and Futuna', value: 'WF' },
  { label: 'Western Sahara', value: 'EH' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
];

export const interestOptions = [
  { label: 'Development', value: 'development' },
  { label: 'Design', value: 'design' },
  { label: 'Frontend', value: 'frontend' },
  { label: 'Backend', value: 'backend' },
  { label: 'Research', value: 'research' },
  { label: 'Marketing', value: 'marketing' },
  { label: 'Intructing', value: 'intructing' },
  { label: 'Project Management', value: 'Project management' },
];

export const passionOptions = [
  { label: 'Technology', value: 'technology' },
  { label: 'Nature', value: 'nature' },
  { label: 'Music', value: 'music' },
  { label: 'Sports', value: 'sports' },
  { label: 'Entreprenuership', value: 'entreprenuership' },
  { label: 'Reading', value: 'reading' },
  { label: 'Volunteering', value: 'volunteering' },
  { label: 'Arts', value: 'arts' },
  { label: 'Dancing', value: 'dancing' },
  { label: 'Comedy', value: 'comedy' },
  { label: 'Gaming', value: 'gaming' },
  { label: 'Cooking', value: 'cooking' },
  { label: 'Animals', value: 'animals' },
  { label: 'Travel', value: 'travel' },
];
export const countriesLoaction = [{ code: 'AF', latitude: 33.0, longitude: 65.0 },
  { code: 'AL', latitude: 41.0, longitude: 20.0 },
  { code: 'DZ', latitude: 28.0, longitude: 3.0 },
  { code: 'AS', latitude: -14.3333, longitude: -170.0 },
  { code: 'AD', latitude: 42.5, longitude: 1.6 },
  { code: 'AO', latitude: -12.5, longitude: 18.5 },
  { code: 'AI', latitude: 18.25, longitude: -63.1667 },
  { code: 'AQ', latitude: -90.0, longitude: 0.0 },
  { code: 'AG', latitude: 17.05, longitude: -61.8 },
  { code: 'AR', latitude: -34.0, longitude: -64.0 },
  { code: 'AM', latitude: 40.0, longitude: 45.0 },
  { code: 'AW', latitude: 12.5, longitude: -69.9667 },
  { code: 'AU', latitude: -27.0, longitude: 133.0 },
  { code: 'AT', latitude: 47.3333, longitude: 13.3333 },
  { code: 'AZ', latitude: 40.5, longitude: 47.5 },
  { code: 'BS', latitude: 24.25, longitude: -76.0 },
  { code: 'BH', latitude: 26.0, longitude: 50.55 },
  { code: 'BD', latitude: 24.0, longitude: 90.0 },
  { code: 'BB', latitude: 13.1667, longitude: -59.5333 },
  { code: 'BY', latitude: 53.0, longitude: 28.0 },
  { code: 'BE', latitude: 50.8333, longitude: 4.0 },
  { code: 'BZ', latitude: 17.25, longitude: -88.75 },
  { code: 'BJ', latitude: 9.5, longitude: 2.25 },
  { code: 'BM', latitude: 32.3333, longitude: -64.75 },
  { code: 'BT', latitude: 27.5, longitude: 90.5 },
  { code: 'BO', latitude: -17.0, longitude: -65.0 },
  { code: 'BA', latitude: 44.0, longitude: 18.0 },
  { code: 'BW', latitude: -22.0, longitude: 24.0 },
  { code: 'BV', latitude: -54.4333, longitude: 3.4 },
  { code: 'BR', latitude: -10.0, longitude: -55.0 },
  { code: 'IO', latitude: -6.0, longitude: 71.5 },
  { code: 'BN', latitude: 4.5, longitude: 114.6667 },
  { code: 'BG', latitude: 43.0, longitude: 25.0 },
  { code: 'BF', latitude: 13.0, longitude: -2.0 },
  { code: 'BI', latitude: -3.5, longitude: 30.0 },
  { code: 'KH', latitude: 13.0, longitude: 105.0 },
  { code: 'CM', latitude: 6.0, longitude: 12.0 },
  { code: 'CA', latitude: 60.0, longitude: -95.0 },
  { code: 'CV', latitude: 16.0, longitude: -24.0 },
  { code: 'KY', latitude: 19.5, longitude: -80.5 },
  { code: 'CF', latitude: 7.0, longitude: 21.0 },
  { code: 'TD', latitude: 15.0, longitude: 19.0 },
  { code: 'CL', latitude: -30.0, longitude: -71.0 },
  { code: 'CN', latitude: 35.0, longitude: 105.0 },
  { code: 'CX', latitude: -10.5, longitude: 105.6667 },
  { code: 'CC', latitude: -12.5, longitude: 96.8333 },
  { code: 'CO', latitude: 4.0, longitude: -72.0 },
  { code: 'KM', latitude: -12.1667, longitude: 44.25 },
  { code: 'CG', latitude: -1.0, longitude: 15.0 },
  { code: 'CD', latitude: 0.0, longitude: 25.0 },
  { code: 'CK', latitude: -21.2333, longitude: -159.7667 },
  { code: 'CR', latitude: 10.0, longitude: -84.0 },
  { code: 'CI', latitude: 8.0, longitude: -5.0 },
  { code: 'HR', latitude: 45.1667, longitude: 15.5 },
  { code: 'CU', latitude: 21.5, longitude: -80.0 },
  { code: 'CY', latitude: 35.0, longitude: 33.0 },
  { code: 'CZ', latitude: 49.75, longitude: 15.5 },
  { code: 'DK', latitude: 56.0, longitude: 10.0 },
  { code: 'DJ', latitude: 11.5, longitude: 43.0 },
  { code: 'DM', latitude: 15.4167, longitude: -61.3333 },
  { code: 'DO', latitude: 19.0, longitude: -70.6667 },
  { code: 'EC', latitude: -2.0, longitude: -77.5 },
  { code: 'EG', latitude: 27.0, longitude: 30.0 },
  { code: 'SV', latitude: 13.8333, longitude: -88.9167 },
  { code: 'GQ', latitude: 2.0, longitude: 10.0 },
  { code: 'ER', latitude: 15.0, longitude: 39.0 },
  { code: 'EE', latitude: 59.0, longitude: 26.0 },
  { code: 'ET', latitude: 8.0, longitude: 38.0 },
  { code: 'FK', latitude: -51.75, longitude: -59.0 },
  { code: 'FO', latitude: 62.0, longitude: -7.0 },
  { code: 'FJ', latitude: -18.0, longitude: 175.0 },
  { code: 'FI', latitude: 64.0, longitude: 26.0 },
  { code: 'FR', latitude: 46.0, longitude: 2.0 },
  { code: 'GF', latitude: 4.0, longitude: -53.0 },
  { code: 'PF', latitude: -15.0, longitude: -140.0 },
  { code: 'TF', latitude: -43.0, longitude: 67.0 },
  { code: 'GA', latitude: -1.0, longitude: 11.75 },
  { code: 'GM', latitude: 13.4667, longitude: -16.5667 },
  { code: 'GE', latitude: 42.0, longitude: 43.5 },
  { code: 'DE', latitude: 51.0, longitude: 9.0 },
  { code: 'GH', latitude: 8.0, longitude: -2.0 },
  { code: 'GI', latitude: 36.1833, longitude: -5.3667 },
  { code: 'GR', latitude: 39.0, longitude: 22.0 },
  { code: 'GL', latitude: 72.0, longitude: -40.0 },
  { code: 'GD', latitude: 12.1167, longitude: -61.6667 },
  { code: 'GP', latitude: 16.25, longitude: -61.5833 },
  { code: 'GU', latitude: 13.4667, longitude: 144.7833 },
  { code: 'GT', latitude: 15.5, longitude: -90.25 },
  { code: 'GG', latitude: 49.5, longitude: -2.56 },
  { code: 'GN', latitude: 11.0, longitude: -10.0 },
  { code: 'GW', latitude: 12.0, longitude: -15.0 },
  { code: 'GY', latitude: 5.0, longitude: -59.0 },
  { code: 'HT', latitude: 19.0, longitude: -72.4167 },
  { code: 'HM', latitude: -53.1, longitude: 72.5167 },
  { code: 'VA', latitude: 41.9, longitude: 12.45 },
  { code: 'HN', latitude: 15.0, longitude: -86.5 },
  { code: 'HK', latitude: 22.25, longitude: 114.1667 },
  { code: 'HU', latitude: 47.0, longitude: 20.0 },
  { code: 'IS', latitude: 65.0, longitude: -18.0 },
  { code: 'IN', latitude: 20.0, longitude: 77.0 },
  { code: 'ID', latitude: -5.0, longitude: 120.0 },
  { code: 'IR', latitude: 32.0, longitude: 53.0 },
  { code: 'IQ', latitude: 33.0, longitude: 44.0 },
  { code: 'IE', latitude: 53.0, longitude: -8.0 },
  { code: 'IM', latitude: 54.23, longitude: -4.55 },
  { code: 'IL', latitude: 31.5, longitude: 34.75 },
  { code: 'IT', latitude: 42.8333, longitude: 12.8333 },
  { code: 'JM', latitude: 18.25, longitude: -77.5 },
  { code: 'JP', latitude: 36.0, longitude: 138.0 },
  { code: 'JE', latitude: 49.21, longitude: -2.13 },
  { code: 'JO', latitude: 31.0, longitude: 36.0 },
  { code: 'KZ', latitude: 48.0, longitude: 68.0 },
  { code: 'KE', latitude: 1.0, longitude: 38.0 },
  { code: 'KI', latitude: 1.4167, longitude: 173.0 },
  { code: 'KP', latitude: 40.0, longitude: 127.0 },
  { code: 'KR', latitude: 37.0, longitude: 127.5 },
  { code: 'KW', latitude: 29.3375, longitude: 47.6581 },
  { code: 'KG', latitude: 41.0, longitude: 75.0 },
  { code: 'LA', latitude: 18.0, longitude: 105.0 },
  { code: 'LV', latitude: 57.0, longitude: 25.0 },
  { code: 'LB', latitude: 33.8333, longitude: 35.8333 },
  { code: 'LS', latitude: -29.5, longitude: 28.5 },
  { code: 'LR', latitude: 6.5, longitude: -9.5 },
  { code: 'LY', latitude: 25.0, longitude: 17.0 },
  { code: 'LI', latitude: 47.1667, longitude: 9.5333 },
  { code: 'LT', latitude: 56.0, longitude: 24.0 },
  { code: 'LU', latitude: 49.75, longitude: 6.1667 },
  { code: 'MO', latitude: 22.1667, longitude: 113.55 },
  { code: 'MK', latitude: 41.8333, longitude: 22.0 },
  { code: 'MG', latitude: -20.0, longitude: 47.0 },
  { code: 'MW', latitude: -13.5, longitude: 34.0 },
  { code: 'MY', latitude: 2.5, longitude: 112.5 },
  { code: 'MV', latitude: 3.25, longitude: 73.0 },
  { code: 'ML', latitude: 17.0, longitude: -4.0 },
  { code: 'MT', latitude: 35.8333, longitude: 14.5833 },
  { code: 'MH', latitude: 9.0, longitude: 168.0 },
  { code: 'MQ', latitude: 14.6667, longitude: -61.0 },
  { code: 'MR', latitude: 20.0, longitude: -12.0 },
  { code: 'MU', latitude: -20.2833, longitude: 57.55 },
  { code: 'YT', latitude: -12.8333, longitude: 45.1667 },
  { code: 'MX', latitude: 23.0, longitude: -102.0 },
  { code: 'FM', latitude: 6.9167, longitude: 158.25 },
  { code: 'MD', latitude: 47.0, longitude: 29.0 },
  { code: 'MC', latitude: 43.7333, longitude: 7.4 },
  { code: 'MN', latitude: 46.0, longitude: 105.0 },
  { code: 'ME', latitude: 42.0, longitude: 19.0 },
  { code: 'MS', latitude: 16.75, longitude: -62.2 },
  { code: 'MA', latitude: 32.0, longitude: -5.0 },
  { code: 'MZ', latitude: -18.25, longitude: 35.0 },
  { code: 'MM', latitude: 22.0, longitude: 98.0 },
  { code: 'NA', latitude: -22.0, longitude: 17.0 },
  { code: 'NR', latitude: -0.5333, longitude: 166.9167 },
  { code: 'NP', latitude: 28.0, longitude: 84.0 },
  { code: 'NL', latitude: 52.5, longitude: 5.75 },
  { code: 'AN', latitude: 12.25, longitude: -68.75 },
  { code: 'NC', latitude: -21.5, longitude: 165.5 },
  { code: 'NZ', latitude: -41.0, longitude: 174.0 },
  { code: 'NI', latitude: 13.0, longitude: -85.0 },
  { code: 'NE', latitude: 16.0, longitude: 8.0 },
  { code: 'NG', latitude: 10.0, longitude: 8.0 },
  { code: 'NU', latitude: -19.0333, longitude: -169.8667 },
  { code: 'NF', latitude: -29.0333, longitude: 167.95 },
  { code: 'MP', latitude: 15.2, longitude: 145.75 },
  { code: 'NO', latitude: 62.0, longitude: 10.0 },
  { code: 'OM', latitude: 21.0, longitude: 57.0 },
  { code: 'PK', latitude: 30.0, longitude: 70.0 },
  { code: 'PW', latitude: 7.5, longitude: 134.5 },
  { code: 'PS', latitude: 32.0, longitude: 35.25 },
  { code: 'PA', latitude: 9.0, longitude: -80.0 },
  { code: 'PG', latitude: -6.0, longitude: 147.0 },
  { code: 'PY', latitude: -23.0, longitude: -58.0 },
  { code: 'PE', latitude: -10.0, longitude: -76.0 },
  { code: 'PH', latitude: 13.0, longitude: 122.0 },
  { code: 'PN', latitude: -24.7, longitude: -127.4 },
  { code: 'PL', latitude: 52.0, longitude: 20.0 },
  { code: 'PT', latitude: 39.5, longitude: -8.0 },
  { code: 'PR', latitude: 18.25, longitude: -66.5 },
  { code: 'QA', latitude: 25.5, longitude: 51.25 },
  { code: 'RE', latitude: -21.1, longitude: 55.6 },
  { code: 'RO', latitude: 46.0, longitude: 25.0 },
  { code: 'RU', latitude: 60.0, longitude: 100.0 },
  { code: 'RW', latitude: -2.0, longitude: 30.0 },
  { code: 'SH', latitude: -15.9333, longitude: -5.7 },
  { code: 'KN', latitude: 17.3333, longitude: -62.75 },
  { code: 'LC', latitude: 13.8833, longitude: -61.1333 },
  { code: 'PM', latitude: 46.8333, longitude: -56.3333 },
  { code: 'VC', latitude: 13.25, longitude: -61.2 },
  { code: 'WS', latitude: -13.5833, longitude: -172.3333 },
  { code: 'SM', latitude: 43.7667, longitude: 12.4167 },
  { code: 'ST', latitude: 1.0, longitude: 7.0 },
  { code: 'SA', latitude: 25.0, longitude: 45.0 },
  { code: 'SN', latitude: 14.0, longitude: -14.0 },
  { code: 'RS', latitude: 44.0, longitude: 21.0 },
  { code: 'SC', latitude: -4.5833, longitude: 55.6667 },
  { code: 'SL', latitude: 8.5, longitude: -11.5 },
  { code: 'SG', latitude: 1.3667, longitude: 103.8 },
  { code: 'SK', latitude: 48.6667, longitude: 19.5 },
  { code: 'SI', latitude: 46.0, longitude: 15.0 },
  { code: 'SB', latitude: -8.0, longitude: 159.0 },
  { code: 'SO', latitude: 10.0, longitude: 49.0 },
  { code: 'ZA', latitude: -29.0, longitude: 24.0 },
  { code: 'GS', latitude: -54.5, longitude: -37.0 },
  { code: 'SS', latitude: 8.0, longitude: 30.0 },
  { code: 'ES', latitude: 40.0, longitude: -4.0 },
  { code: 'LK', latitude: 7.0, longitude: 81.0 },
  { code: 'SD', latitude: 15.0, longitude: 30.0 },
  { code: 'SR', latitude: 4.0, longitude: -56.0 },
  { code: 'SJ', latitude: 78.0, longitude: 20.0 },
  { code: 'SZ', latitude: -26.5, longitude: 31.5 },
  { code: 'SE', latitude: 62.0, longitude: 15.0 },
  { code: 'CH', latitude: 47.0, longitude: 8.0 },
  { code: 'SY', latitude: 35.0, longitude: 38.0 },
  { code: 'TW', latitude: 23.5, longitude: 121.0 },
  { code: 'TJ', latitude: 39.0, longitude: 71.0 },
  { code: 'TZ', latitude: -6.0, longitude: 35.0 },
  { code: 'TH', latitude: 15.0, longitude: 100.0 },
  { code: 'TL', latitude: -8.55, longitude: 125.5167 },
  { code: 'TG', latitude: 8.0, longitude: 1.1667 },
  { code: 'TK', latitude: -9.0, longitude: -172.0 },
  { code: 'TO', latitude: -20.0, longitude: -175.0 },
  { code: 'TT', latitude: 11.0, longitude: -61.0 },
  { code: 'TN', latitude: 34.0, longitude: 9.0 },
  { code: 'TR', latitude: 39.0, longitude: 35.0 },
  { code: 'TM', latitude: 40.0, longitude: 60.0 },
  { code: 'TC', latitude: 21.75, longitude: -71.5833 },
  { code: 'TV', latitude: -8.0, longitude: 178.0 },
  { code: 'UG', latitude: 1.0, longitude: 32.0 },
  { code: 'UA', latitude: 49.0, longitude: 32.0 },
  { code: 'AE', latitude: 24.0, longitude: 54.0 },
  { code: 'GB', latitude: 54.0, longitude: -2.0 },
  { code: 'US', latitude: 38.0, longitude: -97.0 },
  { code: 'UM', latitude: 19.2833, longitude: 166.6 },
  { code: 'UY', latitude: -33.0, longitude: -56.0 },
  { code: 'UZ', latitude: 41.0, longitude: 64.0 },
  { code: 'VU', latitude: -16.0, longitude: 167.0 },
  { code: 'VE', latitude: 8.0, longitude: -66.0 },
  { code: 'VN', latitude: 16.0, longitude: 106.0 },
  { code: 'VG', latitude: 18.5, longitude: -64.5 },
  { code: 'VI', latitude: 18.3333, longitude: -64.8333 },
  { code: 'WF', latitude: -13.3, longitude: -176.2 },
  { code: 'EH', latitude: 24.5, longitude: -13.0 },
  { code: 'YE', latitude: 15.0, longitude: 48.0 },
  { code: 'ZM', latitude: -15.0, longitude: 30.0 },
  { code: 'ZW', latitude: -20.0, longitude: 30.0 }];
