export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGOUT = 'USER_LOGOUT';

// AUTH RELATED
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

// PROFILE RELATED
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const GET_PROFILE = 'GET_PROFILE';

// DONATE AMOUNT RELATED
export const UPDATE_DONATE_AMOUNT = 'UPDATE_DONATE_AMOUNT';

// authModal related
export const AUTHMODAL_START = 'AUTHMODAL_START';
export const AUTHMODAL_SUCCESS = 'AUTHMODAL_SUCCESS';

export const USERS = {
  SET_USER_ADDRESS: 'USERS.SET_USER_ADDRESS',
  FETCH_USER_DETAILS: 'USERS.FETCH_USER_DETAILS',
};

export const SIGNER = {
  UPDATE_CONNECT_STATUS: 'SIGNER.UPDATE_CONNECT_STATUS',
  UPDATE_LOCK_STATUS: 'SIGNER.UPDATE_LOCK_STATUS',
  SET_CONNECT_ERROR: 'SIGNER.SET_CONNECT_ERROR',
  CLEAR_CONNECT_ERROR: 'SIGNER.CLEAR_CONNECT_ERROR',
};

// Wallet RELATED
export const CONNECT_LOADING = 'CONNECT_LOADING';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_ERROR = 'CONNECT_ERROR';
export const DISCONNECT_USER = 'DISCONNECT_USER';
