import {
  ethnicities,
  countries as locations,
  nationalities,
  languages,
  degrees,
  universities,
  status,
  genders,
  softSkills,
  programmingLanguages,
  proficiencies,
} from '../fields';

const all = {
  // profile page details
  firstNameField: {
    name: 'firstName',
    type: 'text',
    label: 'First Name',
    options: [],
    required: false,
    halfWidth: true,
    rightSpaced: true,
  },
  lastNameField: {
    name: 'lastName',
    type: 'text',
    label: 'Last Name',
    options: [],
    required: false,
    halfWidth: true,
  },
  birthdateField: {
    name: 'birthday',
    type: 'date',
    label: 'Date Of Birth',
    options: [],
    required: false,
    halfWidth: true,
    rightSpaced: true,
  },
  genderField: {
    name: 'Gender',
    type: 'select',
    label: 'Gender',
    options: genders,
    required: false,
    halfWidth: true,
  },
  phoneField: {
    name: 'phoneNumber',
    type: 'number',
    label: 'Phone',
    options: [],
    required: false,
    halfWidth: true,
    rightSpaced: true,
  },
  locationField: {
    name: 'location',
    type: 'select',
    label: 'Location',
    options: locations,
    required: false,
    halfWidth: true,
  },
  nationalityField: {
    name: 'Nationality',
    type: 'select',
    label: 'Nationality',
    options: nationalities,
    required: false,
  },
  ethnicityField: {
    name: 'Ethnicity',
    type: 'select',
    label: 'Ethnicity',
    options: ethnicities,
    required: false,
  },

  // profile page overview
  bioField: {
    name: 'bio',
    type: 'textarea',
    label: 'Bio',
    options: [],
    required: false,
  },
  languageField: {
    name: 'primaryLanguage',
    type: 'select',
    label: 'Language',
    options: languages,
    required: false,
  },

  // profile page media
  FacebookLinkField: {
    name: 'FacebookLink',
    type: 'text',
    label: 'Facebook Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  LinkedinLinkField: {
    name: 'LinkedinLink',
    type: 'text',
    label: 'Linkedin Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  GithubLinkField: {
    name: 'GithubLink',
    type: 'text',
    label: 'Github Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  GoogleLinkField: {
    name: 'GoogleLink',
    type: 'text',
    label: 'Google Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  FigmaLinkField: {
    name: 'FigmaLink',
    type: 'text',
    label: 'Figma Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  DribbbleLinkField: {
    name: 'DribbleLink',
    type: 'text',
    label: 'Dribbble Link',
    options: [],
    required: false,
    leftSpaced: true,
  },
  ClickupLinkField: {
    name: 'ClickupLink',
    type: 'text',
    label: 'Clickup Link',
    options: [],
    required: false,
    leftSpaced: true,
  },

  // profile page background
  passionsField: {
    name: 'passions',
    type: 'text',
    label: 'Passions',
    options: [],
    required: false,
    placeholder: 'Passions...',
  },
  softSkillsField: {
    name: 'softSkills',
    type: 'select',
    label: 'Soft Skills',
    options: softSkills,
    required: false,
    placeholder: 'Soft skills',
  },
  programmingLanguagesField: {
    name: 'programmingSkills',
    type: 'select',
    label: 'Programming Skills',
    options: programmingLanguages,
    required: false,
    placeholder: 'Programming skills',
  },
  proficiencyField: {
    name: 'proficiency',
    type: 'select',
    label: 'Proficiency',
    options: proficiencies,
    required: false,
    placeholder: 'Proficiency',
  },

  // profile page education
  educationLevelField: {
    name: 'educationLevel',
    type: 'select',
    label: 'Level of Education',
    options: degrees,
    required: false,
  },
  schoolNameField: {
    name: 'schoolName',
    type: 'text',
    label: 'School Name',
    options: universities,
    required: false,
  },
  enteredHighSchoolYearField: {
    name: 'enteredHighSchoolYear',
    type: 'date',
    label: 'Start Date',
    options: [],
    required: false,
    halfWidth: true,
    rightSpaced: true,
  },
  expectedGraduationYearField: {
    name: 'expectedGraduationYear',
    type: 'date',
    label: 'Graduation Date',
    options: [],
    required: false,
    halfWidth: true,
  },
  studentStatusField: {
    name: 'studentStatus',
    type: 'select',
    label: 'Current Status',
    options: status,
    required: false,
  },
  degreeField: {
    name: 'degree',
    type: 'text',
    label: 'Program of Study',
    options: [],
    required: false,
  },

  // security page login
  emailField: {
    name: 'email',
    type: 'email',
    label: 'Email',
    options: [],
    required: false,
  },
  usernameField: {
    name: 'userName',
    type: 'text',
    label: 'Username',
    options: [],
    required: false,
  },
  currentPasswordField: {
    name: 'currentPassword',
    type: 'password',
    label: 'Current Password',
    options: [],
    required: false,
  },
  newPasswordField: {
    name: 'newPassword',
    type: 'password',
    label: 'New Password',
    options: [],
    required: false,
  },
  confirmNewPasswordField: {
    name: 'confirmNewPassword',
    type: 'password',
    label: 'Confirm New Password',
    options: [],
    required: false,
  },
  // security page management
  // security page privacy
  profileVisibilityField: {
    name: 'profileVisibility',
    type: 'radio',
    label: 'Profile Visiblity',
    options: [],
    required: false,
  },
  birthdayVisibilityField: {
    name: 'birthdayVisibility',
    type: 'radio',
    label: 'Birthdate Visiblity',
    options: [],
    required: false,
  },
  locationVisibilityField: {
    name: 'locationVisibility',
    type: 'radio',
    label: 'Location Visiblity',
    options: [],
    required: false,
  },
  emailVisibilityField: {
    name: 'emailVisibility',
    type: 'radio',
    label: 'Email Visiblity',
    options: [],
    required: false,
  },

  // notifications page notifications
  notifyMessagesField: {
    name: 'notifyMessages',
    type: 'checkbox',
    label: 'Messages',
    options: [],
    required: false,
  },
  notifyAccountActivityField: {
    name: 'notifyAccountActivity',
    type: 'checkbox',
    label: 'Account Activity',
    options: [],
    required: false,
  },
  notifyJobAlertsField: {
    name: 'notifyJobAlerts',
    type: 'checkbox',
    label: 'Job Alerts',
    options: [],
    required: false,
  },
  notifyEventsField: {
    name: 'notifyEvents',
    type: 'checkbox',
    label: 'Events',
    options: [],
    required: false,
  },
};

export default all;
